### ISSUE TITLE
Security: chart values manifest reveals password

### ISSUE THREAD

**Issue by Ibrahimng** [CloudNativeSDWAN/cnwan-helm-charts#14]
Dear Community,

I would like to contribute to the Helm chart by suggesting that all passwords in the values.yaml should be managed with secret using config file (secret.yaml) and it could be reference as a secret name in any of the manifests it is required.

**Blame:** _{Line 91: password: "dem0-pwd"}_ of _CloudNativeSDWAN/cnwan-helm-charts/tree/main/charts/cnwan-operator/values.yaml_

it's a suggestion!

**Comment by SunSince90** [comment]
Hi @Ibrahimng, 

thank you for posting this! We used to use that value as a placeholder for a demo presentation of the project and it is only used when using the chart with etcd. Though I agree that forcing users to choose a password even for a demo is better.

Will be fixing this soon, ty!

**Comment by ljakab** [comment]
Thanks @SunSince90 for the quick fix!!
